spring:
  rabbitmq:
    host: docker.me
    username: guest
    password: guest
    port: 5672
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        output:
          destination: Q1
          producer:
            partitionKeyExpression: payload.groupId
            partitionCount: 3
